import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Carousel } from '../carousel/carousel';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lur</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.carousel}>
        <Carousel />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
